REG-Linux/REG-Linux

- board/batocera/broadcom/linux-defconfig-fragment.config
> Add CONFIG_SQUASHFS_LZ4=y into config fragment to fix non-booting issue

- package/batocera/toolchain/toolchain-optional-linaro-aarch64/toolchain-optional-linaro-aarch64.mk
> Fix Linaro toolchain URL (changed)

- package/batocera/core/batocera-configgen/configs/configgen-defaults-rk3588.yml
Fix error at end of build when checking configs
> Fix rk3588 config (use Dolphin standalone)

- board/batocera/amlogic/s812/patches/mame/switchres-no-xrandr.patch
- package/batocera/emulators/mame/Config.in
- package/batocera/emulators/mame/mame.mk
MAME build on Amlogic S812 was failing because of missing patch + missing pulseaudio dependency
> Fix S812 MAME

- board/batocera/allwinner/h3/orangepi-pc-plus/boot/extlinux.conf
- board/batocera/allwinner/h3/orangepi-pc-plus/create-boot-script.sh
- board/batocera/allwinner/h3/orangepi-pc-plus/genimage.cfg
- board/batocera/amlogic/s905/lepotato/boot/extlinux.conf
- board/batocera/amlogic/s905/nanopi-k2/boot/extlinux.conf
- board/batocera/amlogic/s905/nanopi-k2/build-uboot.sh
- board/batocera/amlogic/s905/nanopi-k2/create-boot-script.sh
- board/batocera/amlogic/s905/nanopi-k2/genimage.cfg
- board/batocera/amlogic/s905gen3/bananapi-m5/boot/extlinux.conf
- board/batocera/amlogic/s905gen3/bananapi-m5/build-uboot.sh
- board/batocera/amlogic/s905gen3/bananapi-m5/create-boot-script.sh
- board/batocera/amlogic/s905gen3/bananapi-m5/genimage.cfg
- Orange Pi PC Plus (@Ntemis will see how to merge with Orange Pi PC to only generate a single image)
- NanoPi K2
- Banana Pi M5
> Add some missing boards

- package/batocera/core/batocera-desktopapps/batocera-desktopapps.mk
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulators/ryujinx/ryujinx.mk
- package/reglinux/emulators/clk/clk.mk
- package/reglinux/reglinux-rescue/reglinux-rescue.mk
- Bump REG-Rescue to 0.4
- Remove vim
- Fix clksignal missing install
- Fix ryujinx "Ava" binary (same hash as main one)
- Disable VCMI for now
> Misc fixes, prepping for a release

- Config.in
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroGenerator.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroMAMEConfig.py
- package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro/libretroOptions.py
- package/batocera/core/batocera-system/Config.in
- package/batocera/emulationstation/batocera-es-system/es_features.yml
- package/batocera/emulationstation/batocera-es-system/es_systems.yml
- package/batocera/emulators/retroarch/libretro-core-info/libretro-core-info.mk
- package/reglinux/emulators/libretro/libretro-geolith/001-makefile.patch
- package/reglinux/emulators/libretro/libretro-geolith/Config.in
- package/reglinux/emulators/libretro/libretro-geolith/libretro-geolith.mk
Hook it up basically into ES.
Take the opportunity to cleanup code referenced mamevirtual / mess cores (deleted) into es_systems/es_features and configgen.
> Initial libretro-geolith support (Accurate NeoGeo emulator)

- package/batocera/emulators/cemu/cemu.mk
- package/batocera/emulators/xemu/xemu.hash
- package/batocera/emulators/xemu/xemu.mk
> Bump cemu and xemu

- package/batocera/emulators/rpcs3/012-savestate-location.patch
- package/batocera/emulators/rpcs3/015-fix-sdl-pad-handler.patch
- package/batocera/emulators/rpcs3/rpcs3.mk
- package/batocera/libraries/faudio/faudio.mk
> Bump RPCS3 (recent SPU improvements) + bump faudio + use system libs for RPCS3

- board/batocera/riscv/visionfive2/dts/jh7110-milkv-mars.dts
- board/batocera/riscv/visionfive2/dts/jh7110-milkv-mars.dts.KO
- configs/batocera-visionfive2.board
Boot OK, HDMI OK, Sound OK, USB 3.0 OK, USB 2.0 KO, Ethernet KO.
> Initial Milk-V Mars (Starfive JH7110 SoC) bringup.

- board/batocera/amlogic/a3gen2/patches/ffmpeg/libv4l-missing-v4l2-type-capture-type.patch
- board/batocera/amlogic/s9gen4/patches/ffmpeg/libv4l-missing-v4l2-type-capture-type.patch
> Fix broken a3gen2/s9gen4 ffmpeg build

- package/reglinux/themes/es-theme-canvas/es-theme-canvas.mk
add: carousel-icons
- chihiro
- cplus4
- ikemen
- mrboom
- pdp1
- singe
- sonicretro
> bump: es-theme-canvas

- package/batocera/emulators/rpcs3/rpcs3.mk
> Bump RPCS3 to 0.0.33

- package/batocera/core/batocera-bluetooth/Config.in
- package/batocera/core/batocera-system/Config.in
Also restore batocera-bluetooth on CHA (removed unintentionally)
> Add bluez_tools package

- package/reglinux/emulators/melonds/melonds.mk
Check: https://github.com/melonDS-emu/melonDS/issues/2017
> MelonDS: fixes polygon flickering when using OpenGL renderer

- package/batocera/emulators/hypseus-singe/hypseus-singe.mk
This reverts commit 3151eed3ebda1a556a3a2dd84bb7e03645611ee4. Needs more work to be able to update properly.
> Revert "hypseus-singe: Update to v2.11.3"

- board/batocera/fsoverlay/etc/ksmbd/ksmbd.conf
- board/batocera/fsoverlay/etc/ksmbd/smb.conf
- sync ksmbd.conf and smb.conf settings
- remove duplicated or unsupported settings
- do not ask user/password to Windows users
> Cleanup samba *.conf and avoid asking credentials

- configs/reglinux-saphira.board
> Cleanup saphira board config

- board/batocera/qualcomm/sm8250/rp5/grub.cfg
- package/reglinux/boot/plymouth/themes/reglinux/reglinux.plymouth
- package/reglinux/reglinux-emulationstation/S31emulationstation
> Avoid rotated logo in portrait screens

- package/reglinux/emulators/vice/000-fix-segfault.patch
Patch should be submitted upstream at VICE team (if not fixed already)
> Fix VICE standalone segfaut using --help

- package/reglinux/reglinux-scripts/scripts/system-format
- package/reglinux/reglinux-scripts/scripts/system-part
- Optimize scripts using internal bash functions instead of piping to sed or grep
> Avoid grep|sed pipelines using bash var manipulation

- package/emulators/libretro/libretro-cap32/libretro-cap32.mk
- package/emulators/libretro/libretro-fceumm/libretro-fceumm.mk
- package/emulators/libretro/libretro-mame2003-plus/libretro-mame2003-plus.mk
- package/emulators/libretro/libretro-puae/libretro-puae.mk
- package/emulators/libretro/libretro-puae2021/libretro-puae2021.mk
- package/emulators/libretro/libretro-vice/libretro-vice.mk
Various emulation fixes and improvements
> Some lr cores fixes

- board/mediatek/mt8395/patches/alsa-ucm-conf/001-wip-mt8395-evk-sof.patch
> WIP alsa ucm/ucm2 conf for mt8395
